"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */

    await queryInterface.bulkInsert(
      "Utilities",
      [
        {
          utilities_id: 2,
          house_id: 10,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: true,
          fire_protection: true,
          parking: false,
          camera: false,
        },
        {
          utilities_id: 5,
          house_id: 13,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 6,
          house_id: 14,
          bedrooms: 2,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 7,
          house_id: 15,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 8,
          house_id: 16,
          bedrooms: 1,
          floors: 2,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 9,
          house_id: 17,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 10,
          house_id: 18,
          bedrooms: 1,
          floors: 6,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 13,
          house_id: 21,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: false,
          camera: false,
        },
        {
          utilities_id: 14,
          house_id: 22,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: false,
          camera: false,
        },
        {
          utilities_id: 15,
          house_id: 23,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 16,
          house_id: 24,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: true,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 17,
          house_id: 25,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: true,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 18,
          house_id: 26,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 19,
          house_id: 27,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 20,
          house_id: 28,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 21,
          house_id: 29,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: true,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 22,
          house_id: 30,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 23,
          house_id: 31,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: true,
          camera: false,
        },
        {
          utilities_id: 24,
          house_id: 32,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: false,
          fire_protection: false,
          parking: true,
          camera: true,
        },
        {
          utilities_id: 25,
          house_id: 33,
          bedrooms: 1,
          floors: 1,
          bathrooms: 1,
          security: true,
          fire_protection: true,
          parking: true,
          camera: true,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
